
import EnumValue = require('dw/value/EnumValue')
import MarkupText = require('dw/content/MarkupText');
import MediaFile = require('dw/content/MediaFile');

// autogeneratedfile - '/home/risto/Documents/salesforce/cartridgesHub/pointspay_sfra/metadata/pointspayMetadata/meta/system-objecttype-extensions.xml'
declare global {
    module ICustomAttributes {

		interface PaymentMethod {
			/**
			* Environment
			* @group Pointspay - Pointspay
			* @source [attribute](file:/home/risto/Documents/salesforce/cartridgesHub/pointspay_sfra/metadata/pointspayMetadata/meta/system-objecttype-extensions.xml#5) | [group](file:/home/risto/Documents/salesforce/cartridgesHub/pointspay_sfra/metadata/pointspayMetadata/meta/system-objecttype-extensions.xml#85)
			*/
			pointspayEnvironment: EnumValue<'TEST' | 'LIVE' | null> 

			/**
			* Live shop code
			* @group Pointspay - Pointspay
			* @source [attribute](file:/home/risto/Documents/salesforce/cartridgesHub/pointspay_sfra/metadata/pointspayMetadata/meta/system-objecttype-extensions.xml#19) | [group](file:/home/risto/Documents/salesforce/cartridgesHub/pointspay_sfra/metadata/pointspayMetadata/meta/system-objecttype-extensions.xml#86)
			*/
			pointspayLiveShopCode: string | null;

			/**
			* Test shop code
			* @group Pointspay - Pointspay
			* @source [attribute](file:/home/risto/Documents/salesforce/cartridgesHub/pointspay_sfra/metadata/pointspayMetadata/meta/system-objecttype-extensions.xml#26) | [group](file:/home/risto/Documents/salesforce/cartridgesHub/pointspay_sfra/metadata/pointspayMetadata/meta/system-objecttype-extensions.xml#87)
			*/
			pointspayTestShopCode: string | null;

			/**
			* Live consumer key
			* @group Pointspay - Pointspay
			* @source [attribute](file:/home/risto/Documents/salesforce/cartridgesHub/pointspay_sfra/metadata/pointspayMetadata/meta/system-objecttype-extensions.xml#33) | [group](file:/home/risto/Documents/salesforce/cartridgesHub/pointspay_sfra/metadata/pointspayMetadata/meta/system-objecttype-extensions.xml#88)
			*/
			pointspayLiveConsumerKey: string | null;

			/**
			* Test consumer key
			* @group Pointspay - Pointspay
			* @source [attribute](file:/home/risto/Documents/salesforce/cartridgesHub/pointspay_sfra/metadata/pointspayMetadata/meta/system-objecttype-extensions.xml#40) | [group](file:/home/risto/Documents/salesforce/cartridgesHub/pointspay_sfra/metadata/pointspayMetadata/meta/system-objecttype-extensions.xml#89)
			*/
			pointspayTestConsumerKey: string | null;

			/**
			* Live private key
			* @group Pointspay - Pointspay
			* @source [attribute](file:/home/risto/Documents/salesforce/cartridgesHub/pointspay_sfra/metadata/pointspayMetadata/meta/system-objecttype-extensions.xml#47) | [group](file:/home/risto/Documents/salesforce/cartridgesHub/pointspay_sfra/metadata/pointspayMetadata/meta/system-objecttype-extensions.xml#90)
			*/
			pointspayLivePrivateKey: string | null;

			/**
			* Test private key
			* @group Pointspay - Pointspay
			* @source [attribute](file:/home/risto/Documents/salesforce/cartridgesHub/pointspay_sfra/metadata/pointspayMetadata/meta/system-objecttype-extensions.xml#54) | [group](file:/home/risto/Documents/salesforce/cartridgesHub/pointspay_sfra/metadata/pointspayMetadata/meta/system-objecttype-extensions.xml#91)
			*/
			pointspayTestPrivateKey: string | null;

			/**
			* Live Pointspay public key
			* @group Pointspay - Pointspay
			* @source [attribute](file:/home/risto/Documents/salesforce/cartridgesHub/pointspay_sfra/metadata/pointspayMetadata/meta/system-objecttype-extensions.xml#61) | [group](file:/home/risto/Documents/salesforce/cartridgesHub/pointspay_sfra/metadata/pointspayMetadata/meta/system-objecttype-extensions.xml#92)
			*/
			pointspayLivePublicKey: string | null;

			/**
			* Test Pointspay public key
			* @group Pointspay - Pointspay
			* @source [attribute](file:/home/risto/Documents/salesforce/cartridgesHub/pointspay_sfra/metadata/pointspayMetadata/meta/system-objecttype-extensions.xml#68) | [group](file:/home/risto/Documents/salesforce/cartridgesHub/pointspay_sfra/metadata/pointspayMetadata/meta/system-objecttype-extensions.xml#93)
			*/
			pointspayTestPublicKey: string | null;

			/**
			* Debug mode
			* @group Pointspay - Pointspay
			* @source [attribute](file:/home/risto/Documents/salesforce/cartridgesHub/pointspay_sfra/metadata/pointspayMetadata/meta/system-objecttype-extensions.xml#75) | [group](file:/home/risto/Documents/salesforce/cartridgesHub/pointspay_sfra/metadata/pointspayMetadata/meta/system-objecttype-extensions.xml#94)
			*/
			pointspayDebugMode: boolean | null;

		}
		interface Order {
			/**
			* Pointspay redirect URL
			* 
			* @source [attribute](file:/home/risto/Documents/salesforce/cartridgesHub/pointspay_sfra/metadata/pointspayMetadata/meta/system-objecttype-extensions.xml#100) 
			*/
			pointspayRedirectUrl: string | null;

		}
	}
}

declare global {
	interface IGetCustomPreferenceValue {
		
	}
}